plugins:
  - babel
  - jest
env:
  node: true
  jest: true
parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
rules:
  no-console: 0
  arrow-parens: 0
  implicit-arrow-linebreak: 0
  no-unused-vars: 1
  consistent-return: 0